[package]
authors = ["Charles Ray <icedpygui@gmail.com>"]
name = "IcedPyGui"
version = "0.1.0"
edition = "2021"

[lib]
name = "icedpygui"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.20.3"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[dependencies]
iced = { version = "0.12.1", features = ["advanced", "debug", "highlighter", "image", 
                                        "lazy", "smol", "svg", "multi-window"] }
iced_aw = { version = "0.8.0", features = ["card", "color_picker", "icons",]}
rfd = "0.12"
once_cell = "1.19.0"
chrono = "0.4.31"
num-traits = "0.2"
unicode-segmentation = "1.9.0"
